# The configuration
configuration:
    source_dir: content               # The directory containing MKD files
    build_dir: build                  # The directory where the site is build
    template_dir: templates/current   # The directory containing the templates
    bibtex_dir: content/bibtex        # The directory containing BibTeX files
    static_dir: static                # The directory containing static content
    site_root: /build/                    # The website root


# The pages (in order)
pages:
    - title:
        en: Home
        fr: Accueil
      file_prefix: index
      navigation: yes

    - title:
        en: People
        fr: Membres
      file_prefix: people
      navigation: yes

    - title:
        en: Projects
        fr: Projets
      file_prefix: projects
      navigation: yes

    - title:
        en: Publications
        fr: Publications
      file_prefix: publications
      navigation: yes
      template: publications.html
      bibtex: yes

    - title:
        en: Tools
        fr: Outils
      file_prefix: tools
      navigation: yes


# Finds all pages inside the directory
autodiscover:
    - directory: people
      title:
        en: People
        fr: Membres

    - directory: tools
      title:
        en: Tools
        fr: Outils
